part-2/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :products, only: [:new, :index, :show, :create] do
    resources :product_features, only: [:new, :create]
  end
  root to: 'products#index'
end

part-2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

part-2/app/models/feature.rb
class Feature < ApplicationRecord
  has_many :product_features
end

part-2/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :product_features, dependent: :destroy
  has_many :features, through: :product_features
end

part-2/app/models/product_feature.rb
class ProductFeature < ApplicationRecord
  belongs_to :product
  belongs_to :feature
end

part-2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_many :products
end

part-2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

part-2/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

part-2/app/controllers/product_features_controller.rb
class ProductFeaturesController < ApplicationController
  before_action :set_product, only: [:create]

  def create
    @product_feature = ProductFeature.new(product_feature_params)
    @product_feature.product = @product
    if @product_feature.save
      redirect_to product_path(@product)
    else
      render 'products/show'
    end
  end

  private

  def product_feature_params
    params.require(:product_feature).permit(:product_id, :description, :feature_id)
  end

  def set_product
    @product = Product.find(params[:product_id])
  end
end

part-2/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_product, only: [:show]

  def index
    @feature_names = Feature.all.map { |feature| feature.name.to_sym }
    products = Product.includes(:product_features).includes(:features)
    @result = products.map do |product|
      features = product.product_features.map do |product_feature|
        { product_feature.feature.name.to_sym => product_feature.description }
      end
      {
        "id": product.id,
        "features": features.reduce({}, :merge)
      }
    end
    # render json: @result
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(user: current_user)
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end


  def show
    @product_feature = ProductFeature.new
    @product_features = @product.product_features.includes(:feature)
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end
end

part-2/app/helpers/application_helper.rb
module ApplicationHelper
end

part-2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>TODO</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <!-- <script src="https://cdn.jsdelivr.net/npm/vue"></script> -->
  <%#= javascript_pack_tag 'hello_vue' %>
</body>
</html>

part-2/app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

part-2/app/views/products/index.html.erb
<div class="container">
  <h1>All Products</h1>
  <table class="blueTable">
    <thead>
      <tr>
        <th>Product ID</th>
        <% @feature_names.each do |name| %>
        <th><%= name %></th>
        <% end %>
      </tr>
    </thead>
    <% @result.each do |product| %>
    <tbody>
      <tr class="product">
        <td>Product #<%= product[:id] %></td>
        <% @feature_names.each do |name| %>
        <td><%= product[:features][name] %></td>
        <% end %>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

part-2/app/views/products/new.html.erb
<div class="container">
  <h1>New Product</h1>
  <%= simple_form_for(@product) do |f| %>
  <%= f.submit "Create!", class: "btn btn-primary" %>
  <% end %>
</div>

part-2/app/views/products/show.html.erb
<div class="container">
  <h1>Product <%= @product.id %></h1>
  <h2>Add attributes</h2>
  <%= simple_form_for [@product, @product_feature] do |f| %>
  <%= f.association :feature, collection: Feature.all.order(:name), prompt: "Choose an attribute" %>

  <%= f.input :description %>
  <%= f.submit "Add an attribute", class: "btn btn-primary" %>
  <% end %>
</div>


<hr>
<div class="container">
  <h4>Attributes</h4>
  <ul>
    <% @product_features.each do |product_feature| %>
    <li><%= product_feature.feature.name %> -
      <%= product_feature.description %>
    </li>
    <% end %>
  </ul>
</div>

part-2/app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

part-2/app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "New product", new_product_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/lionel-k", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>